F
======================================================================
FAIL: test_main (main.tests.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\programming\project\main\tests.py", line 5, in test_main
    self.assertEqual(True, False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
